version: '3.2'
services:
  web:
    build: 
      context: .                    
      dockerfile: Dockerfile
    image: electron-server
    container_name: electron-server
    restart: always
  
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database_production

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
volumes:
  db-data: