version: "3.2"
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: swim
      MYSQL_ROOT_PASSWORD: 123456
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9000:8080
    depends_on: # 启动顺序
      - db
    networks: # 加入指定网络
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: electron-server
    container_name: electron-server
    restart: always
    ports:
      - 7001:7001
    depends_on:
      - db
      - adminer
    links:
      - db:db
      - adminer:adminer
    networks:
      - app-network

volumes:
  db-data:

networks: # 实现通信
  app-network:
    driver: bridge
